### ISSUE TITLE
Прошу проверить ДЗ #7: Поиск недвижимости

### ISSUE THREAD

**Issue by Lagunov-PRO** [Lagunov-PRO/HW07_Realty_Finder#3]
@coursar
Ильназ, здравствуйте!

Реализовал получение координат объектов через API  Яндекс.Карт. По формуле гаверсинусов рассчитываю расстояния до станций метро. Получившиеся словари храню в виде JSON. Поиск по ближайшим 3-м станциям и/или по цене есть. Есть возможность добавления объявлений вручную или через редактирование CSV  файла. При запуске программы сравнивается хэш этого CSV файла  и JSON полностью обновляется.

**Comment by coursar** [comment]
Отлично, ключевое замечание - не завязываться в тестах и в функциях на конкретные пути к файлам и к данным внутри этих файлов
